// Seeds réalistes pour le mock store. Couvrent un mix de scénarios que les
// agents A→F peuvent exploiter dès Phase 1. Si une fonctionnalité a besoin
// de plus de cas (ex. annulations multiples, conflits OTA), enrichis ici
// plutôt que d'inventer en place.

import type {
  Channel,
  Guest,
  Invoice,
  Message,
  Notification,
  Promo,
  Rate,
  Reservation,
  Room,
  Staff,
  Task,
} from "./types";

// Notre référence temporelle = aujourd'hui. Les seeds calculent leurs dates
// relativement à cette base pour rester pertinents quel que soit le moment
// où l'on ouvre l'admin.
const TODAY = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);
const day = (delta: number) => {
  const d = new Date(TODAY);
  d.setDate(d.getDate() + delta);
  return iso(d);
};
const ts = (delta: number) => {
  const d = new Date(TODAY);
  d.setHours(d.getHours() + delta);
  return d.toISOString();
};

// ─── Staff ─────────────────────────────────────────────────────────────

export const seedStaff: Staff[] = [
  {
    id: "user_direction",
    email: "direction@notre-hotel.com",
    firstName: "Yasmine",
    lastName: "Benali",
    role: "direction",
    shift: "flexible",
    active: true,
    avatarInitials: "YB",
    password: "demo",
    createdAt: "2024-01-15T09:00:00.000Z",
  },
  {
    id: "user_manager",
    email: "manager@notre-hotel.com",
    firstName: "Karim",
    lastName: "Hamadi",
    role: "manager",
    shift: "flexible",
    active: true,
    avatarInitials: "KH",
    password: "demo",
    createdAt: "2024-02-02T09:00:00.000Z",
  },
  {
    id: "user_marie",
    email: "marie@notre-hotel.com",
    firstName: "Marie",
    lastName: "Cherif",
    role: "reception",
    shift: "matin",
    active: true,
    avatarInitials: "MC",
    password: "demo",
    createdAt: "2024-02-10T09:00:00.000Z",
  },
  {
    id: "user_samir",
    email: "samir@notre-hotel.com",
    firstName: "Samir",
    lastName: "Touati",
    role: "reception",
    shift: "apres-midi",
    active: true,
    avatarInitials: "ST",
    password: "demo",
    createdAt: "2024-03-04T09:00:00.000Z",
  },
  {
    id: "user_aicha",
    email: "aicha@notre-hotel.com",
    firstName: "Aïcha",
    lastName: "Bouzid",
    role: "gouvernante",
    shift: "matin",
    active: true,
    avatarInitials: "AB",
    password: "demo",
    createdAt: "2024-01-22T09:00:00.000Z",
  },
  {
    id: "user_fatima",
    email: "fatima@notre-hotel.com",
    firstName: "Fatima",
    lastName: "Mezari",
    role: "gouvernante",
    shift: "matin",
    active: true,
    avatarInitials: "FM",
    password: "demo",
    createdAt: "2024-02-14T09:00:00.000Z",
  },
  {
    id: "user_nadia",
    email: "nadia@notre-hotel.com",
    firstName: "Nadia",
    lastName: "Rabia",
    role: "comptabilite",
    shift: "matin",
    active: true,
    avatarInitials: "NR",
    password: "demo",
    createdAt: "2024-04-01T09:00:00.000Z",
  },
];

// ─── Rooms ─────────────────────────────────────────────────────────────
// 30 chambres sur 4 étages pour rester lisible (le vrai hôtel en a 124).

function generateRooms(): Room[] {
  const list: Room[] = [];
  const layout: Array<{
    floor: number;
    nums: string[];
    type: Room["type"];
    publicSlug?: Room["publicSlug"];
  }> = [
    {
      floor: 1,
      nums: ["101", "102", "103", "104"],
      type: "double",
      publicSlug: "chambre-double-vue",
    },
    {
      floor: 1,
      nums: ["105", "106"],
      type: "twin",
      publicSlug: "chambre-twin",
    },
    {
      floor: 2,
      nums: ["201", "202", "203", "204"],
      type: "double",
      publicSlug: "chambre-double-vue",
    },
    {
      floor: 2,
      nums: ["205", "206"],
      type: "single",
      publicSlug: "chambre-single",
    },
    {
      floor: 2,
      nums: ["207"],
      type: "familiale",
      publicSlug: "chambre-familiale",
    },
    {
      floor: 3,
      nums: ["301", "302", "303"],
      type: "double",
      publicSlug: "chambre-double-vue",
    },
    {
      floor: 3,
      nums: ["304", "305"],
      type: "triple",
    },
    {
      floor: 3,
      nums: ["306", "307"],
      type: "suite",
      publicSlug: "suite-senior",
    },
    {
      floor: 4,
      nums: ["401", "402"],
      type: "suite",
      publicSlug: "suite-senior",
    },
    {
      floor: 4,
      nums: ["403", "404"],
      type: "appartement",
      publicSlug: "appartement",
    },
    {
      floor: 4,
      nums: ["405", "406", "407", "408", "409"],
      type: "double",
      publicSlug: "chambre-double-vue",
    },
  ];

  // Distribution de statuts approximative : 55 % occupé, 20 % libre/propre,
  // 12 % à nettoyer, 6 % inspection, 4 % maintenance, 3 % OOO.
  const statuses: Room["status"][] = [
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "occupied",
    "vacant-clean",
    "vacant-clean",
    "vacant-clean",
    "vacant-clean",
    "vacant-clean",
    "vacant-clean",
    "vacant-dirty",
    "vacant-dirty",
    "vacant-dirty",
    "vacant-dirty",
    "vacant-dirty",
    "inspection",
    "inspection",
    "maintenance",
    "maintenance",
    "out-of-order",
    "occupied",
    "occupied",
    "occupied",
  ];

  let i = 0;
  for (const block of layout) {
    for (const num of block.nums) {
      const status = statuses[i % statuses.length] ?? "vacant-clean";
      list.push({
        number: num,
        floor: block.floor,
        type: block.type,
        publicSlug: block.publicSlug,
        status,
        lastCleanedAt:
          status === "vacant-dirty" ? undefined : ts(-Math.floor(Math.random() * 24)),
        note:
          status === "out-of-order"
            ? "Climatisation à remplacer — fournisseur attendu vendredi."
            : status === "maintenance"
              ? "Fuite robinet salle de bain — plombier sur place."
              : undefined,
        availableFrom: status === "out-of-order" ? day(3) : undefined,
      });
      i++;
    }
  }
  return list;
}

export const seedRooms: Room[] = generateRooms();

// ─── Guests ────────────────────────────────────────────────────────────

export const seedGuests: Guest[] = [
  {
    id: "g_amrani",
    firstName: "Lina",
    lastName: "Amrani",
    email: "lina.amrani@example.com",
    phone: "+213 555 12 34 56",
    nationality: "Algérienne",
    language: "fr",
    dob: "1989-04-12",
    idNumber: "AL-789-2310",
    address: "Rue des Frères Bouchama, Alger",
    loyaltyTier: "or",
    loyaltyPoints: 1840,
    preferences: ["Chambre haute", "Oreiller ferme", "Petit-déjeuner tardif"],
    notes: [
      {
        id: "gn_1",
        body: "Cliente fidèle, prévoit toujours une arrivée vers 22h. Prévenir la nuit.",
        author: "user_marie",
        createdAt: ts(-24 * 32),
        kind: "preference",
      },
    ],
    documents: [
      {
        id: "doc_1",
        kind: "id",
        label: "Carte d'identité (recto-verso)",
        uploadedAt: ts(-24 * 90),
        uploadedBy: "user_marie",
      },
    ],
    createdAt: ts(-24 * 365),
    totalStays: 8,
    totalSpentDA: 412_500,
    vip: true,
  },
  {
    id: "g_dupont",
    firstName: "Camille",
    lastName: "Dupont",
    email: "camille.dupont@example.com",
    phone: "+33 6 12 34 56 78",
    nationality: "Française",
    language: "fr",
    loyaltyTier: "argent",
    loyaltyPoints: 620,
    preferences: ["Lit double ferme", "Étage calme"],
    notes: [],
    documents: [
      {
        id: "doc_2",
        kind: "passport",
        label: "Passeport — page identité",
        uploadedAt: ts(-24 * 12),
        uploadedBy: "user_samir",
      },
    ],
    createdAt: ts(-24 * 180),
    totalStays: 3,
    totalSpentDA: 78_400,
    vip: false,
  },
  {
    id: "g_meziane",
    firstName: "Sofiane",
    lastName: "Meziane",
    email: "s.meziane@example.com",
    phone: "+213 661 22 88 09",
    nationality: "Algérienne",
    language: "fr",
    loyaltyTier: "bronze",
    loyaltyPoints: 120,
    preferences: ["Wi-Fi haut débit", "Bureau"],
    notes: [
      {
        id: "gn_2",
        body: "Voyage d'affaires. Demande factures séparées par nuit.",
        author: "user_nadia",
        createdAt: ts(-24 * 8),
        kind: "general",
      },
    ],
    documents: [],
    createdAt: ts(-24 * 60),
    totalStays: 2,
    totalSpentDA: 24_900,
    vip: false,
  },
  {
    id: "g_oconnor",
    firstName: "Sean",
    lastName: "O'Connor",
    email: "sean@example.com",
    phone: "+44 7700 900 123",
    nationality: "Irlandaise",
    language: "en",
    loyaltyPoints: 0,
    preferences: ["Vue panoramique"],
    notes: [],
    documents: [],
    createdAt: ts(-24 * 4),
    totalStays: 0,
    totalSpentDA: 0,
    vip: false,
  },
  {
    id: "g_belkacem",
    firstName: "Yacine",
    lastName: "Belkacem",
    email: "y.belkacem@example.com",
    phone: "+213 770 45 67 89",
    nationality: "Algérienne",
    language: "ar",
    loyaltyTier: "platine",
    loyaltyPoints: 5240,
    preferences: ["Suite Senior", "Service en chambre 19h"],
    notes: [
      {
        id: "gn_3",
        body: "VIP — anniversaire de mariage prévu lors du prochain séjour.",
        author: "user_direction",
        createdAt: ts(-24 * 2),
        kind: "vip",
      },
    ],
    documents: [
      {
        id: "doc_3",
        kind: "id",
        label: "Carte d'identité",
        uploadedAt: ts(-24 * 365),
        uploadedBy: "user_marie",
      },
    ],
    createdAt: ts(-24 * 700),
    totalStays: 22,
    totalSpentDA: 1_240_000,
    vip: true,
  },
  {
    id: "g_arrouche",
    firstName: "Salima",
    lastName: "Arrouche",
    email: "salima.a@example.com",
    phone: "+213 550 89 12 34",
    nationality: "Algérienne",
    language: "fr",
    loyaltyTier: "argent",
    loyaltyPoints: 480,
    preferences: ["Chambre famille", "Berceau"],
    notes: [],
    documents: [],
    createdAt: ts(-24 * 90),
    totalStays: 2,
    totalSpentDA: 41_200,
    vip: false,
  },
];

// ─── Reservations ──────────────────────────────────────────────────────

export const seedReservations: Reservation[] = [
  {
    id: "res_001",
    ref: "RES-2026-AM12X",
    status: "checked-in",
    source: "direct",
    guestId: "g_amrani",
    roomNumber: "306",
    roomType: "suite",
    checkIn: day(-1),
    checkOut: day(2),
    adults: 2,
    children: 0,
    ratePerNightDA: 12_500,
    totalDA: 37_500 + 1800, // 3 nuits + taxe séjour
    paidDA: 39_300,
    addOnIds: ["breakfast"],
    arrivalTime: "21:30",
    notes: "Cliente fidèle, vue confirmée.",
    createdAt: ts(-24 * 14),
    createdBy: "user_marie",
  },
  {
    id: "res_002",
    ref: "RES-2026-DP78Z",
    status: "arrival-expected",
    source: "booking-com",
    guestId: "g_dupont",
    roomNumber: "201",
    roomType: "double",
    checkIn: day(0),
    checkOut: day(3),
    adults: 2,
    children: 0,
    ratePerNightDA: 8_300,
    totalDA: 24_900 + 1800,
    paidDA: 0,
    addOnIds: [],
    arrivalTime: "16:00",
    notes: "Arrivée par avion 14h05.",
    createdAt: ts(-24 * 6),
    createdBy: "user_samir",
  },
  {
    id: "res_003",
    ref: "RES-2026-MZ44Q",
    status: "confirmed",
    source: "direct",
    guestId: "g_meziane",
    roomNumber: "205",
    roomType: "single",
    checkIn: day(2),
    checkOut: day(5),
    adults: 1,
    children: 0,
    ratePerNightDA: 7_300,
    totalDA: 21_900 + 900,
    paidDA: 21_900,
    addOnIds: ["airport-pickup"],
    notes: "Mission de 3 jours. Factures séparées par nuit demandées.",
    createdAt: ts(-24 * 3),
    createdBy: "user_marie",
  },
  {
    id: "res_004",
    ref: "RES-2026-OC11A",
    status: "option",
    source: "phone",
    guestId: "g_oconnor",
    roomType: "suite",
    checkIn: day(7),
    checkOut: day(10),
    adults: 2,
    children: 0,
    ratePerNightDA: 12_500,
    totalDA: 37_500 + 1800,
    paidDA: 0,
    addOnIds: [],
    holdUntil: day(2),
    notes: "Option à confirmer avant mardi 18h.",
    createdAt: ts(-24 * 1),
    createdBy: "user_samir",
  },
  {
    id: "res_005",
    ref: "RES-2026-BK99M",
    status: "checked-in",
    source: "expedia",
    guestId: "g_belkacem",
    roomNumber: "401",
    roomType: "suite",
    checkIn: day(-2),
    checkOut: day(1),
    adults: 2,
    children: 1,
    ratePerNightDA: 12_500,
    totalDA: 37_500 + 2700,
    paidDA: 40_200,
    addOnIds: ["breakfast", "champagne"],
    notes: "VIP. Préparer fleurs à l'arrivée.",
    createdAt: ts(-24 * 30),
    createdBy: "user_direction",
  },
  {
    id: "res_006",
    ref: "RES-2026-AR22Y",
    status: "departure-expected",
    source: "direct",
    guestId: "g_arrouche",
    roomNumber: "207",
    roomType: "familiale",
    checkIn: day(-3),
    checkOut: day(0),
    adults: 2,
    children: 2,
    ratePerNightDA: 9_300,
    totalDA: 27_900 + 3600,
    paidDA: 31_500,
    addOnIds: ["breakfast"],
    notes: "Famille avec deux enfants — berceau fourni.",
    createdAt: ts(-24 * 12),
    createdBy: "user_marie",
  },
  {
    id: "res_007",
    ref: "RES-2026-LST3B",
    status: "no-show",
    source: "booking-com",
    guestId: "g_meziane",
    roomNumber: undefined,
    roomType: "double",
    checkIn: day(-5),
    checkOut: day(-3),
    adults: 1,
    children: 0,
    ratePerNightDA: 8_300,
    totalDA: 16_600 + 600,
    paidDA: 0,
    addOnIds: [],
    notes: "Client jamais arrivé. Booking notifié.",
    createdAt: ts(-24 * 10),
    createdBy: "user_samir",
  },
  {
    id: "res_008",
    ref: "RES-2026-CN44L",
    status: "cancelled",
    source: "direct",
    guestId: "g_dupont",
    roomType: "double",
    checkIn: day(-12),
    checkOut: day(-10),
    adults: 2,
    children: 0,
    ratePerNightDA: 8_300,
    totalDA: 16_600,
    paidDA: 0,
    addOnIds: [],
    notes: "Annulée par la cliente — changement de programme.",
    createdAt: ts(-24 * 20),
    createdBy: "user_marie",
    modifiedAt: ts(-24 * 14),
  },
];

// ─── Tasks ─────────────────────────────────────────────────────────────

export const seedTasks: Task[] = [
  {
    id: "t_001",
    kind: "housekeeping",
    priority: "high",
    status: "pending",
    roomNumber: "102",
    title: "Recouchage complet après départ",
    body: "Linge à changer, salle de bain à refaire à fond.",
    assignedTo: "user_aicha",
    createdBy: "user_marie",
    createdAt: ts(-2),
    dueAt: ts(2),
  },
  {
    id: "t_002",
    kind: "housekeeping",
    priority: "normal",
    status: "in-progress",
    roomNumber: "201",
    title: "Préparation chambre avant arrivée",
    body: "Vérifier amenities + bouteille d'eau + fleurs (VIP).",
    assignedTo: "user_fatima",
    createdBy: "user_marie",
    createdAt: ts(-3),
    dueAt: ts(1),
  },
  {
    id: "t_003",
    kind: "maintenance",
    priority: "urgent",
    status: "in-progress",
    roomNumber: "405",
    title: "Climatisation HS",
    body: "Pas de froid depuis hier soir. Locataire en a fait mention.",
    assignedTo: "user_manager",
    createdBy: "user_aicha",
    createdAt: ts(-6),
    dueAt: ts(4),
  },
  {
    id: "t_004",
    kind: "housekeeping",
    priority: "normal",
    status: "done",
    roomNumber: "302",
    title: "Recouchage standard",
    assignedTo: "user_aicha",
    createdBy: "user_marie",
    createdAt: ts(-8),
    completedAt: ts(-4),
  },
  {
    id: "t_005",
    kind: "maintenance",
    priority: "low",
    status: "pending",
    roomNumber: "103",
    title: "Ampoule chambre à changer",
    assignedTo: "user_manager",
    createdBy: "user_fatima",
    createdAt: ts(-1),
  },
  {
    id: "t_006",
    kind: "maintenance",
    priority: "high",
    status: "blocked",
    roomNumber: "407",
    title: "Remplacement clim — attente fournisseur",
    body: "Référence commandée, livraison vendredi.",
    assignedTo: "user_manager",
    createdBy: "user_direction",
    createdAt: ts(-48),
    resolution: undefined,
  },
];

// ─── Invoices ──────────────────────────────────────────────────────────

export const seedInvoices: Invoice[] = [
  {
    id: "inv_001",
    ref: "F-2026-001",
    reservationId: "res_001",
    guestId: "g_amrani",
    status: "partial",
    items: [
      {
        id: "it_1",
        label: "Suite Senior — 3 nuits",
        qty: 3,
        unitPriceDA: 12_500,
        totalDA: 37_500,
        source: "room",
        addedAt: ts(-24),
      },
      {
        id: "it_2",
        label: "Taxe de séjour (2 pers · 3 nuits)",
        qty: 6,
        unitPriceDA: 300,
        totalDA: 1_800,
        source: "tax",
        addedAt: ts(-24),
      },
      {
        id: "it_3",
        label: "Petit-déjeuner supplémentaire",
        qty: 1,
        unitPriceDA: 1_800,
        totalDA: 1_800,
        source: "addon",
        addedAt: ts(-24),
      },
      {
        id: "it_4",
        label: "Restaurant — Dîner soir 1",
        qty: 1,
        unitPriceDA: 4_200,
        totalDA: 4_200,
        source: "pos-restaurant",
        addedAt: ts(-12),
      },
    ],
    payments: [
      {
        id: "pay_1",
        method: "card",
        amountDA: 39_300,
        receivedAt: ts(-23),
        takenBy: "user_marie",
      },
    ],
    issuedAt: ts(-24),
    totalDA: 45_300,
    paidDA: 39_300,
    balanceDA: 6_000,
  },
  {
    id: "inv_002",
    ref: "F-2026-002",
    reservationId: "res_005",
    guestId: "g_belkacem",
    status: "paid",
    items: [
      {
        id: "it_5",
        label: "Suite Senior — 3 nuits",
        qty: 3,
        unitPriceDA: 12_500,
        totalDA: 37_500,
        source: "room",
        addedAt: ts(-48),
      },
      {
        id: "it_6",
        label: "Taxe de séjour (3 pers · 3 nuits)",
        qty: 9,
        unitPriceDA: 300,
        totalDA: 2_700,
        source: "tax",
        addedAt: ts(-48),
      },
    ],
    payments: [
      {
        id: "pay_2",
        method: "transfer",
        amountDA: 40_200,
        receivedAt: ts(-47),
        takenBy: "user_nadia",
      },
    ],
    issuedAt: ts(-48),
    totalDA: 40_200,
    paidDA: 40_200,
    balanceDA: 0,
  },
];

// ─── Rates ─────────────────────────────────────────────────────────────

export const seedRates: Rate[] = [
  {
    id: "rate_basse_double",
    roomType: "double",
    season: "basse",
    weekdayDA: 7_500,
    weekendDA: 8_300,
    startsOn: "2026-01-15",
    endsOn: "2026-03-15",
    label: "Hiver — Chambre Double",
  },
  {
    id: "rate_moy_double",
    roomType: "double",
    season: "moyenne",
    weekdayDA: 8_300,
    weekendDA: 9_200,
    startsOn: "2026-03-16",
    endsOn: "2026-06-15",
    label: "Printemps — Chambre Double",
  },
  {
    id: "rate_haute_double",
    roomType: "double",
    season: "haute",
    weekdayDA: 9_500,
    weekendDA: 11_000,
    startsOn: "2026-06-16",
    endsOn: "2026-09-15",
    label: "Été — Chambre Double",
  },
  {
    id: "rate_basse_suite",
    roomType: "suite",
    season: "basse",
    weekdayDA: 11_500,
    weekendDA: 12_500,
    startsOn: "2026-01-15",
    endsOn: "2026-03-15",
    label: "Hiver — Suite Senior",
  },
  {
    id: "rate_haute_suite",
    roomType: "suite",
    season: "haute",
    weekdayDA: 14_000,
    weekendDA: 16_500,
    startsOn: "2026-06-16",
    endsOn: "2026-09-15",
    label: "Été — Suite Senior",
  },
  {
    id: "rate_basse_appart",
    roomType: "appartement",
    season: "basse",
    weekdayDA: 14_500,
    weekendDA: 15_500,
    startsOn: "2026-01-15",
    endsOn: "2026-03-15",
    label: "Hiver — Appartement",
  },
  {
    id: "rate_haute_appart",
    roomType: "appartement",
    season: "haute",
    weekdayDA: 17_500,
    weekendDA: 19_500,
    startsOn: "2026-06-16",
    endsOn: "2026-09-15",
    label: "Été — Appartement",
  },
];

// ─── Promos ────────────────────────────────────────────────────────────

export const seedPromos: Promo[] = [
  {
    id: "pr_week3",
    code: "WEEK3",
    label: "3e nuit offerte (longs séjours)",
    kind: "free-night",
    value: 1,
    startsOn: "2026-01-01",
    endsOn: "2026-12-31",
    usageCount: 42,
    active: true,
  },
  {
    id: "pr_work10",
    code: "WORKWEEK10",
    label: "Tarif affaires — 10 % du lundi au jeudi",
    kind: "percent",
    value: 10,
    startsOn: "2026-01-01",
    endsOn: "2026-12-31",
    usageCount: 18,
    active: true,
  },
  {
    id: "pr_mariage10",
    code: "MARIAGE10",
    label: "Tarif groupe mariage",
    kind: "percent",
    value: 10,
    startsOn: "2026-04-01",
    endsOn: "2026-10-31",
    usageCount: 6,
    usageLimit: 200,
    active: true,
  },
  {
    id: "pr_famille15",
    code: "FAMILLE15",
    label: "Famille — 15 % sur la seconde chambre",
    kind: "percent",
    value: 15,
    startsOn: "2026-06-01",
    endsOn: "2026-09-15",
    usageCount: 3,
    active: true,
  },
  {
    id: "pr_arch",
    code: "OPEN2025",
    label: "Lancement (archivé)",
    kind: "percent",
    value: 20,
    startsOn: "2025-01-01",
    endsOn: "2025-12-31",
    usageCount: 89,
    active: false,
  },
];

// ─── Channels ──────────────────────────────────────────────────────────

export const seedChannels: Channel[] = [
  {
    id: "ch_booking",
    name: "Booking.com",
    enabled: true,
    status: "synced",
    lastSyncedAt: ts(-1),
    inventorySynced: 28,
    totalInventory: 30,
    commissionPct: 17,
  },
  {
    id: "ch_expedia",
    name: "Expedia",
    enabled: true,
    status: "warn",
    lastSyncedAt: ts(-6),
    inventorySynced: 22,
    totalInventory: 30,
    statusMessage: "8 chambres non synchronisées — relance prévue.",
    commissionPct: 18,
  },
  {
    id: "ch_airbnb",
    name: "Airbnb",
    enabled: false,
    status: "off",
    inventorySynced: 0,
    totalInventory: 0,
    commissionPct: 14,
  },
  {
    id: "ch_direct",
    name: "Site direct",
    enabled: true,
    status: "synced",
    lastSyncedAt: ts(0),
    inventorySynced: 30,
    totalInventory: 30,
    commissionPct: 0,
  },
];

// ─── Messages ──────────────────────────────────────────────────────────

export const seedMessages: Message[] = [
  {
    id: "msg_1",
    threadId: "thr_amrani",
    guestId: "g_amrani",
    channel: "email",
    direction: "inbound",
    subject: "Arrivée tardive ce soir",
    body: "Bonjour, nous serons à l'hôtel vers 22h. Merci de prévenir la réception.",
    sentAt: ts(-3),
    readAt: ts(-2),
  },
  {
    id: "msg_2",
    threadId: "thr_amrani",
    guestId: "g_amrani",
    channel: "email",
    direction: "outbound",
    subject: "Re: Arrivée tardive ce soir",
    body: "Bonjour Madame Amrani, c'est noté. La nuit est prévenue, votre Suite vous attend. Bon voyage.",
    sentAt: ts(-2.5),
    sentBy: "user_marie",
  },
  {
    id: "msg_3",
    threadId: "thr_dupont",
    guestId: "g_dupont",
    channel: "sms",
    direction: "outbound",
    body: "Bonjour, votre chambre 201 est prête. À tout à l'heure — Hôtel Notre Hôtel.",
    sentAt: ts(-4),
    sentBy: "user_samir",
  },
  {
    id: "msg_4",
    threadId: "thr_oconnor",
    guestId: "g_oconnor",
    channel: "email",
    direction: "inbound",
    subject: "Honeymoon options",
    body: "Hello, we are considering booking a suite for our honeymoon — could you confirm availability?",
    sentAt: ts(-12),
  },
];

// ─── Notifications ─────────────────────────────────────────────────────

export const seedNotifications: Notification[] = [
  {
    id: "not_1",
    kind: "reservation",
    severity: "info",
    title: "Nouvelle réservation — RES-2026-OC11A",
    body: "Option à confirmer avant mardi 18h.",
    link: "/admin/reservations/res_004",
    createdAt: ts(-1),
    audience: ["reception", "manager", "direction"],
  },
  {
    id: "not_2",
    kind: "task",
    severity: "warn",
    title: "Climatisation 405 — urgent",
    body: "Intervention demandée depuis 6h.",
    link: "/admin/chambres/maintenance",
    createdAt: ts(-6),
    audience: ["gouvernante", "manager", "direction"],
  },
  {
    id: "not_3",
    kind: "channel",
    severity: "warn",
    title: "Expedia — 8 chambres non synchronisées",
    body: "Risque de double-booking si non résolu.",
    link: "/admin/tarifs/canaux",
    createdAt: ts(-6),
    audience: ["manager", "direction"],
  },
  {
    id: "not_4",
    kind: "payment",
    severity: "info",
    title: "Acompte reçu — RES-2026-AM12X",
    body: "39 300 DA par carte.",
    link: "/admin/facturation/inv_001",
    createdAt: ts(-23),
    readAt: ts(-22),
    audience: ["reception", "comptabilite"],
  },
];
